import React, { useEffect, useState } from 'react';

const AsciiArt: React.FC = () => {
    const [screenSize, setScreenSize] = useState<string>('small');

    useEffect(() => {
        const handleResize = () => {
            const width = window.innerWidth;
            if (width < 768) {
                setScreenSize('small');
            } else if (width < 1200) {
                setScreenSize('medium');
            } else {
                setScreenSize('large');
            }
        };

        // Initial check
        handleResize();

        // Add event listener
        window.addEventListener('resize', handleResize);

        // Cleanup
        return () => window.removeEventListener('resize', handleResize);
    }, []);

    const smallAscii = `&YYYYYYYYYYYYYYYYYYYYYYYYYYY555Y555YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYP##BBBBGGPY55PPYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYPB&&##&#&&#BP#BPGP55YYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYY5B#&#&&&@@@@&&&@@&@#BPY5YYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYB&##&&@&&&@&&&&@@&&##BPG5YYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYY5&@@#GGBBBBB#BBGGBGGPG#BPYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYP&@@B5555PPPP5J?7??JB&&B5YYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYY5#&B5555555YY?~~~~~!5##GYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYGB5B##@&&&BPPB###GP5G#PYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYPPYG###&###?P&@&##GP?Y?YYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYY5P5Y5PGGBBP?^:JGPY??!^JYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYY5PJJJYY5PPY?J?YYJ?7^!?YYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYGPJJYGBGGPPGPPGPJ??55YYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYY5GP5PBGP55YJJ5GGYY5PYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYPGGBBP5PPY?!!YPPPP5YYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYG#BBGGG5YJ?JPGG5YYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYGBBBBBGBGGGGG5!JYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYJ5YYYY5PP55YY55J?7^~?JYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYJJJ??7?YYYJJJJ???77777!~^^~!77?JYYYYYYYYYYYYYYYY#
&YYYYYYYYYJJJ?777777???7777??JJJ????777!^^^:.   .:^!?JYYYYYYYYYYY#
&YYYYYJJ!:.^!!777777???????7777!!!!!??~^^:.          .:^!?YYYYYYY#
&YY7~^..   ^!!7777777??????????777J5Y~^:.                 .~?YYYY#
&Y~        .^!7777777777777777!!?5PJ~^.                      :JYY#
#^::..... .:~!!!!77777777777!7?Y5Y7^.                   ....  .?Y#
#^~7^:^.:^:^!!!!!!!!~!!!!!!!?55Y7^.                    .:. ..: .J&
#7!!7~^^!7~!7777!~~~!!7!!!?55Y7^.                 . ....^:.:~:^ :#
#77777!~!7!77!!^~~~^::~~~7??7^.  .......          ....: ^^.:!:~: B
#7!7777!!7!!~^~~^^:  .^!??7~. ................ .      ..:~::~^!^ B`;

    const mediumAscii = `&YJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJJYYYYYJYYYYYYYYYJJJJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5BB#BGGBGPPGP555YY5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYP#&&#B##B##BGBPYGG5PBG5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5G#&&&&##&&&&@&&#BPB&BPGP5555YYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYP#&&&##&&&@@@@@&&@&&@@@@@@BGB5YYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYY5##B##&&@&&&&@@@&&&&&@@@@@&##BP5PGYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYB&&&#&&&@@&&&&&@&&&&&&@&&##BBBBPGPYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYY5&@@@&#PPGBBGBBB####BGGBBGGG5PBBBGYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYY5&@@@&G55555PPPPPP555YJYYJJP#&&&BPYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYY5&&&&#P555555PPP55Y?!!~!7??YB#&#G5YYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYB&&G5Y5555555YYYJ?~^~~~~^~75###GYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYY5#B5GBBB&&&&&#BP55GBBBBBP55YP##PYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYY5#PYP&#&&&@@@&@B5B@@@@@&&&BBYGYJYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYY5YP5Y5BGBBB&#BB#Y^?#B&#BBGP5Y^YJ?YYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYY55GYYY5GGGBBBBG?~::!PGP5J7??~^?YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG5JYYY55555PJ?7!!~!5JJJ?7!^^7?YYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYJPGYJJJJJYPGB#BP5PGY55YJJ?7!7YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5BGYJJYP#BGPPPPPPP5PB#5JJJJ5PYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPGP555BBGBPP5YYJJPGP#PYY55P5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGPPPPBB5Y5555Y?77?5G55555PYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPBBBBBBG5PGG5J?!^~JPPGPPPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5B#BBGBGGGYJJ??JJ5GGGGYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ5B#BBBBBGBB#BGGGGGGGJ!YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5PGB#BBGPPPPPPGGP5Y~~YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYJY5YYYJJYYY55555YYYYYJ??!^^^7JJYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYYYYYYYJJJ??77J5YYYJJJJJ?????7777777!~~^~~!7JJJYYYYYYYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYYYYYYYJJ???777?7??777?JJJYJJJJJ????????777~^^^^^:   :^~7?JYYYYYYYYYYYYYYYYYYY#
&YYYYYYYYYYYYJ???77!!!7777???????77!!777?????????777!!!^^^^:.         .:~7JJYYYYYYYYYYYYYY#
&YYYYYYYYYY7:. ^!!77777777777????????777!!!!!!!!~!?J!~^^^:.                .:~?JYYYYYYYYYY#
&YYYYJ?!^:.    ^!77777777777???????????????77777J557^^^:.                      .^!?YYYYYYY#
&YY7:.         :^~!7777777777777????????777777?5P57^^:.                            :!YYYYY#
&Y7:  .....     .~77777777777777777777777!!!?5PPY!~^.            ..                  :JYYY#
&!.^: ......  ..^!!!77777777777777777777!!?YPPY?~^.                            ....   .?YY#
#::^!:.:^... .::^!!~~!!!!!!!!!!!!!!!!!!!?YP5Y?!^.                            ... .. .. .JY#
#^~!77^.^:.^~~.^!!!!777777!~~~~!!!!~~!?5P5Y?!^.                      ........::.. .:.^. :J#
#7!7!77~^~^!7!^!777777!!~^~~!!777777J5P5Y?!^.                           .... .^:..^~::~  :#
#777!777!!~!7!!7777!!^^^~!!~^^!!~^!?JJ??!^.   ....... .             ........ .~^..:!~.!:  B
#7!7!77!7!~!7!!777~~^~!~~^... .:^7?7777~.   .............                ..:. ~~.::~!:!~  B
#7!!77777!!!7!!7~^:!!^:^:..  .^7?????!:  ...............: .::.....         ...^~^:^~~:!~. B`;
    const largeAscii = `&YJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJJJJJJYYYJYYYJJJJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY55PPPPYY55555P55YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG#####GGB#BGPGPGP55555YY55YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG#&&#BB###GB##GGGBG5YGGP5PBBBP5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5G#&@&&###&&#BB&&###BG55B##GJ5P55P5JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYP#&&&&&&&##&&&@@@@@&@&#&#5G@@&BGBB5PP5PPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5G#&&&&###&&&&@@@&&@@@&@@&#&@@&@@@@@&BG#GPY5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG#BB####&&@@&&@&&&@@@&&&&&&&@@@@&@@@&BB#P5J5P5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYP######&&&&@&@&&##&@@@&&&&&&&@@@&&@&###&#BBPPG#5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYB&&&&#&&&#&&@@&&&&&&&@#&&&&&&&@@&&###B##BBBPPGPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5&@@@@@&#GGGBB#BBBB####&#####BBB#BBBBBPYYPBBBBG5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG&&@@@@&B5555555PPPPPPGGPPGP5555555555PBB####BGYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG&&@@@&#G55555555PPPPPP55555YJ?JJJJJJYG#&&&&BG5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG&&&&&&BP5555555PPPPPPP555J777!~77??7JPB##&#GGYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5#&&&#G55555555555YYYYYYY?~^:^~^^^!!!7YB####BPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG#&#PYY55PPPGGGGPP5YYJJ?77!777777~^^!7JG###B5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5##BYG###B#@@@@@@@&#BGP5PB#&&&&&##BGPPJ5###BYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5##5Y5B@&&&@@@@@@@@@@BPP#@@@@@@@@&&&#G&PPBG5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJYYP#YYYP#BB####@&####&G??#&##@&#####BGPG^Y5~!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGYYBYY55GGGGGGB&#BBBBG?^.7BBB&#BBBG5YJ5?^!55YJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5YPPJYYY5GGGGBBGBBBB57~^.:~5BGPP5Y77?J?^^~YYJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYBGJYYY555PGGGPPPPJ77!~~^^^?5YJ??77!!~^^~?7YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYBYJYYYYJJYJJYYPPYYYJ????7J5YJYYJ??7^^^77JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY#PYJJJJJJJJ5PGB#&#BP5PBBPY55YJJJJJ7!!!J5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5BBG5JJJJJ5B#BGGPPPPPPGGG55PBBBYJJ????YP5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYBBP5YYYYG#BB#G55YYYYYY55GGGB&BYJJJY5PG5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5GPPP555G#GPGGGPP5Y5J?JYPP5GBPYYY555P5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGPPPPPPBBG5YYYYYYYYJ77!7JYPG5YY55YYPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPBGGGGBBBGP55PPPGPP5YJ7!!J5PPPPP55P5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYG#BB#BB#BGPPPGG5?7!~^^^~75GPPGGPG5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYP###BBGGBBBGG5JJYYJ?JJYYPGGGGGYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ5###BBBBBBBGGGBBBGGGGGGGGGGGY!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPB#####BGBBGBGBBBGGGGGGGPG57^JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5PGGBBBGBGP555555PPPGPPYY?~^7YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJY5YYYYYYJJJYY555PP5555YY55P5Y?777!^^^^7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJJ?7?Y55YYYYJJJJJJJ????JJ?????7777777~~^^^~~!7?JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJJ???777777?YYYYYJJJJJJJJJ????7777777?777!~~~^^~^^~~!7!!7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYYYYYYJJ???777777??????77!7?JJYYYJJJJJJJ???????????77777~^::^^^^^     .:^~!?JYYYYYYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYYYYYYYJJ?77!!!777777??????????77!!!!7??JJJJJJJJJ????????7!!7~^^^^^^^.            .:~7?YYYYYYYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYYYJ?!~^^!!!!!77777777777???????????777!!!!!!!77777777!!!~!?!!~~^^^^^:                   .^~!?JYYYYYYYYYYYYYYYYYY&
&YYYYYYYYYYYYYY7.    ~!!77777777777777777????????????77777!!!!!!~~~!!7J5?~~^^^^^:.                         .^!?JYYYYYYYYYYYYYY&
&YYYYYYYYJ?~::.     .^!777777777777777?????????????????????77777777?YPPJ~^^^^^:.                               .^!JYYYYYYYYYYY&
&YYYY?!^:.           ^!!!!77777777777777????????????????????777777JPPPY~^^^^:.                                     :!?YYYYYYYY&
&YYY!              ...::^!!!!77777777777777777777777777777777!!7J5P55Y~^^^:.                                          ^JYYYYYY&
&YY!:  .........      .^!777777777777777777777777777777777!!!!J5PPP5?~~~:.              .......                        :?YYYYY&
&Y~.^:  ........    ..:~!77777777777777777777777777777777!!!J5P555J!~~^.                                       ....      !YYYY&
&~..:!:..:::...:.  .::^~!!!!!!!!!!7777777777777777!77!!!!7J55555J!~~^.                                       .. ....      7YYY&
&^.:^!7^..^~:.:.. .:::^~!!!~~!!!!!!!!!!!!!!!!!!!!!!!!!!7J5P555J!~~^.                                       .:...  ......   ?YY&
&^^~~!77^:.^~..:^~~^ ^!!!!!!777777777!~~~~~~~~~~~~~~~!J55555J!!~^.                              .....  .....::... .....^.  .?Y&
&7!!!!!77!^:!::~!77~:~777777777777!~~^~~~^!!!!!!!!!7Y5P555J!~~^.                                  .  ...... :^:.: .:^: ^~.  .J&
&77777!777!^~~^!77!!~!7777777!!~~^::~~!!!777777!!7YPP555J7!~^.   .                               .  ....... :^:.:..^!~..!^   .#
&?!777!7777!!!^~77!!!7777!!!!^::^~!!77!::~!!!~^^!??JJ??7!!^   .  ........   ..                  ... ..:.... .~^::..:!!^.!~.  .#
&?!777!777!7!!~~77!!!77777!~^^~!7!!~^:....^^::~77777777!^    .................                     ....:::.  ~~^..:.!!~.!!^  .#
&7!!777777!77!~!77!~!7!7!^^~~!!^^^^... .   .^7?7??77?!^.  . ................ ... .....                  ..:. ^~^:.^:^!~.!!~. .#
&7!7!777777!7!!!77!!77~^::~!!^.:^^...  ...~??77?????^. .. .. ....::...........::  .::..........           ...^~~~.:^~!^.!!~: .#`;

    return (
        <div id="preComp">
            <pre id="small-screen" style={{ display: screenSize === 'small' ? 'block' : 'none' }}>
                {smallAscii}
            </pre>
            <pre id="medium-screen" style={{ display: screenSize === 'medium' ? 'block' : 'none' }}>
                {mediumAscii}
            </pre>
            <pre id="large-screen" style={{ display: screenSize === 'large' ? 'block' : 'none' }}>
                {largeAscii}
            </pre>
        </div>
    );
}

export default AsciiArt;