import React, { useEffect, useRef } from 'react';
import portrait from '../../data/portrait.json';
import '../../styles/main-page.css';

/**
 * The portrait, as characters. Two fixed grids — 78 columns and 46 — swapped by
 * a CSS media query rather than a resize listener, so there's no JS running and
 * no flash of the wrong size on first paint. The narrow grid exists because
 * scaling the wide one down to fit a phone makes the glyphs unreadably small.
 *
 * Art is generated by personal-assistant/tools/ascii-portrait.py; change the
 * source photo or that script, never the strings.
 *
 * A sparse flicker keeps it from just sitting there like a photo: each tick a
 * handful of glyphs swap to another character from the generator's own ramp
 * and revert shortly after, like static — never the whole grid at once.
 */

// Same shading ramp ascii-portrait.py draws from, minus the blank end — only
// visible characters flicker.
const FLICKER_RAMP = '.·:-=+*#%@';

/** Wires up the flicker on one <pre>; a no-op under reduced motion. */
function useFlicker(ref: React.RefObject<HTMLPreElement | null>, text: string) {
    useEffect(() => {
        const el = ref.current;
        if (!el) return;

        if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

        const original = Array.from(text);
        const chars = original.slice();

        const interval = window.setInterval(() => {
            const n = 20 + Math.floor(Math.random() * 12);
            for (let k = 0; k < n; k++) {
                const i = Math.floor(Math.random() * chars.length);
                if (/\s/.test(original[i])) continue;
                chars[i] = FLICKER_RAMP[Math.floor(Math.random() * FLICKER_RAMP.length)];
            }
            el.textContent = chars.join('');

            window.setTimeout(() => {
                chars.splice(0, chars.length, ...original);
                el.textContent = chars.join('');
            }, 150);
        }, 180);

        return () => window.clearInterval(interval);
    }, [ref, text]);
}

const AsciiArt: React.FC = () => {
    const wideRef = useRef<HTMLPreElement>(null);
    const narrowRef = useRef<HTMLPreElement>(null);

    useFlicker(wideRef, portrait.wide);
    useFlicker(narrowRef, portrait.narrow);

    return (
        <div id="preComp">
            <pre ref={wideRef} className="ascii-portrait is-wide" aria-label="ASCII portrait of Pedro Serdio Hank">
                {portrait.wide}
            </pre>
            <pre ref={narrowRef} className="ascii-portrait is-narrow" aria-hidden="true">
                {portrait.narrow}
            </pre>
        </div>
    );
};

export default AsciiArt;
