import React from 'react';
import portrait from '../../data/portrait.json';
import '../../styles/main-page.css';

/**
 * The portrait, as characters. Two fixed grids — 78 columns and 46 — swapped by
 * a CSS media query rather than a resize listener, so there's no JS running and
 * no flash of the wrong size on first paint. The narrow grid exists because
 * scaling the wide one down to fit a phone makes the glyphs unreadably small.
 *
 * Art is generated by personal-assistant/tools/ascii-portrait.py; change the
 * source photo or that script, never the strings.
 */
const AsciiArt: React.FC = () => (
    <div id="preComp">
        <pre className="ascii-portrait is-wide" aria-label="ASCII portrait of Pedro Serdio Hank">
            {portrait.wide}
        </pre>
        <pre className="ascii-portrait is-narrow" aria-hidden="true">
            {portrait.narrow}
        </pre>
    </div>
);

export default AsciiArt;
